/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IYieldVenueExecutor,
  IYieldVenueExecutorInterface,
} from "../../PolicyRouter.sol/IYieldVenueExecutor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minOutputAmount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "executeDeposit",
    outputs: [
      {
        internalType: "uint256",
        name: "outputAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IYieldVenueExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IYieldVenueExecutorInterface {
    return new Interface(_abi) as IYieldVenueExecutorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IYieldVenueExecutor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IYieldVenueExecutor;
  }
}
