import { NextRequest, NextResponse } from "next/server";
import { rateLimit, getClientKey } from "../../../lib/rate-limit";
import { z } from "zod";

// In-memory store: UUID → pending PDF job (2-minute TTL)
const pending = new Map<string, {
  content: string;
  address: string;
  date: string;
  expiresAt: number;
}>();

function cleanup() {
  const now = Date.now();
  for (const [k, v] of pending) {
    if (v.expiresAt < now) pending.delete(k);
  }
}

const bodySchema = z.object({
  content: z.string().min(1).max(20_000),
  address: z.string().min(10),
});

// POST — store content, return a single-use UUID
export async function POST(request: NextRequest) {
  const { allowed } = rateLimit(getClientKey(request), 10, 60_000);
  if (!allowed) return NextResponse.json({ error: "Too many requests" }, { status: 429 });

  const parsed = bodySchema.safeParse(await request.json().catch(() => ({})));
  if (!parsed.success) return NextResponse.json({ error: "Invalid request" }, { status: 400 });

  cleanup();
  const id = crypto.randomUUID();
  pending.set(id, {
    ...parsed.data,
    date: new Date().toISOString().slice(0, 10),
    expiresAt: Date.now() + 2 * 60 * 1000,
  });

  return NextResponse.json({ id });
}

// GET ?id=UUID — generate and stream PDF with real HTTPS headers
export async function GET(request: NextRequest) {
  const id = request.nextUrl.searchParams.get("id") ?? "";
  const entry = pending.get(id);

  if (!entry || Date.now() > entry.expiresAt) {
    return new NextResponse("Link expired — please generate again.", { status: 404 });
  }
  pending.delete(id); // single-use

  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  const usableW = pageW - margin * 2;
  let y = 22;

  // Header bar
  doc.setFillColor(61, 214, 140);
  doc.rect(0, 0, pageW, 16, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text("AKILI — AI Financial Copilot", margin, 10.5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Wallet Statement", pageW - margin, 10.5, { align: "right" });

  // Meta
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(8);
  doc.text(`Wallet: ${entry.address}`, margin, y);
  y += 5;
  doc.text(
    `Network: Celo Mainnet  ·  Generated: ${new Date().toLocaleString("en-US", { dateStyle: "long", timeStyle: "short" })}`,
    margin, y
  );
  y += 2;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y + 2, pageW - margin, y + 2);
  y += 7;

  // Body
  for (const raw of entry.content.split("\n")) {
    if (y > 272) { doc.addPage(); y = 20; }
    const line = raw.trimStart();

    if (line.startsWith("### ")) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(30, 30, 30);
      doc.text(line.slice(4), margin, y);
      y += 6;
    } else if (line.startsWith("- ") || line.startsWith("• ")) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const wrapped = doc.splitTextToSize("• " + line.slice(2).replace(/\*\*/g, ""), usableW - 4);
      doc.text(wrapped, margin + 2, y);
      y += (wrapped as string[]).length * 5;
    } else if (line === "") {
      y += 2;
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      const wrapped = doc.splitTextToSize(line.replace(/\*\*/g, ""), usableW);
      doc.text(wrapped, margin, y);
      y += (wrapped as string[]).length * 5;
    }
  }

  // Footer on every page
  const totalPages = (doc.internal as unknown as { getNumberOfPages: () => number }).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const ph = doc.internal.pageSize.getHeight();
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, ph - 12, pageW - margin, ph - 12);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Akili · akilii-minipay.vercel.app", margin, ph - 7);
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, ph - 7, { align: "right" });
  }

  const bytes = doc.output("arraybuffer");
  const filename = `akili-statement-${entry.address.slice(0, 6)}-${entry.date}.pdf`;

  return new NextResponse(bytes, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}
