/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PolicyRouter {
  export type ExecutionRequestStruct = {
    user: AddressLike;
    action: BigNumberish;
    venueIdHash: BytesLike;
    token: AddressLike;
    amount: BigNumberish;
    minOutputAmount: BigNumberish;
    quoteTimestamp: BigNumberish;
    quoteExpiresAt: BigNumberish;
    maxSlippageBps: BigNumberish;
    recipient: AddressLike;
  };

  export type ExecutionRequestStructOutput = [
    user: string,
    action: bigint,
    venueIdHash: string,
    token: string,
    amount: bigint,
    minOutputAmount: bigint,
    quoteTimestamp: bigint,
    quoteExpiresAt: bigint,
    maxSlippageBps: bigint,
    recipient: string
  ] & {
    user: string;
    action: bigint;
    venueIdHash: string;
    token: string;
    amount: bigint;
    minOutputAmount: bigint;
    quoteTimestamp: bigint;
    quoteExpiresAt: bigint;
    maxSlippageBps: bigint;
    recipient: string;
  };

  export type VenuePolicyStruct = {
    enabled: boolean;
    executor: AddressLike;
    maxAmount: BigNumberish;
    cooldownSeconds: BigNumberish;
    maxQuoteAgeSeconds: BigNumberish;
    minUserRiskScore: BigNumberish;
    requiresRecipientMatch: boolean;
  };

  export type VenuePolicyStructOutput = [
    enabled: boolean,
    executor: string,
    maxAmount: bigint,
    cooldownSeconds: bigint,
    maxQuoteAgeSeconds: bigint,
    minUserRiskScore: bigint,
    requiresRecipientMatch: boolean
  ] & {
    enabled: boolean;
    executor: string;
    maxAmount: bigint;
    cooldownSeconds: bigint;
    maxQuoteAgeSeconds: bigint;
    minUserRiskScore: bigint;
    requiresRecipientMatch: boolean;
  };
}

export interface PolicyRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowedTokens"
      | "executePolicyAction"
      | "lastExecutionAt"
      | "owner"
      | "paused"
      | "policyAdmins"
      | "setAllowedToken"
      | "setPaused"
      | "setPolicyAdmin"
      | "setUserRiskScore"
      | "setVenuePolicy"
      | "transferOwnership"
      | "userRiskScores"
      | "venuePolicies"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnerTransferred"
      | "PolicyActionExecuted"
      | "PolicyAdminSet"
      | "RouterPaused"
      | "TokenAllowed"
      | "UserRiskScoreSet"
      | "VenuePolicySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executePolicyAction",
    values: [PolicyRouter.ExecutionRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "lastExecutionAt",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyAdmins",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedToken",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "setPolicyAdmin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserRiskScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVenuePolicy",
    values: [BytesLike, PolicyRouter.VenuePolicyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRiskScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "venuePolicies",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executePolicyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastExecutionAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVenuePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRiskScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "venuePolicies",
    data: BytesLike
  ): Result;
}

export namespace OwnerTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyActionExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    venueIdHash: BytesLike,
    action: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    venueIdHash: string,
    action: bigint,
    token: string,
    amount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    user: string;
    venueIdHash: string;
    action: bigint;
    token: string;
    amount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyAdminSetEvent {
  export type InputTuple = [admin: AddressLike, allowed: boolean];
  export type OutputTuple = [admin: string, allowed: boolean];
  export interface OutputObject {
    admin: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouterPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenAllowedEvent {
  export type InputTuple = [token: AddressLike, allowed: boolean];
  export type OutputTuple = [token: string, allowed: boolean];
  export interface OutputObject {
    token: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRiskScoreSetEvent {
  export type InputTuple = [user: AddressLike, riskScore: BigNumberish];
  export type OutputTuple = [user: string, riskScore: bigint];
  export interface OutputObject {
    user: string;
    riskScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VenuePolicySetEvent {
  export type InputTuple = [
    venueIdHash: BytesLike,
    executor: AddressLike,
    enabled: boolean,
    maxAmount: BigNumberish,
    cooldownSeconds: BigNumberish,
    maxQuoteAgeSeconds: BigNumberish,
    minUserRiskScore: BigNumberish,
    requiresRecipientMatch: boolean
  ];
  export type OutputTuple = [
    venueIdHash: string,
    executor: string,
    enabled: boolean,
    maxAmount: bigint,
    cooldownSeconds: bigint,
    maxQuoteAgeSeconds: bigint,
    minUserRiskScore: bigint,
    requiresRecipientMatch: boolean
  ];
  export interface OutputObject {
    venueIdHash: string;
    executor: string;
    enabled: boolean;
    maxAmount: bigint;
    cooldownSeconds: bigint;
    maxQuoteAgeSeconds: bigint;
    minUserRiskScore: bigint;
    requiresRecipientMatch: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyRouter extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyRouter;
  waitForDeployment(): Promise<this>;

  interface: PolicyRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  executePolicyAction: TypedContractMethod<
    [request: PolicyRouter.ExecutionRequestStruct],
    [bigint],
    "nonpayable"
  >;

  lastExecutionAt: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  policyAdmins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  setAllowedToken: TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setPaused: TypedContractMethod<[nextPaused: boolean], [void], "nonpayable">;

  setPolicyAdmin: TypedContractMethod<
    [admin: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setUserRiskScore: TypedContractMethod<
    [user: AddressLike, riskScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVenuePolicy: TypedContractMethod<
    [venueIdHash: BytesLike, policy: PolicyRouter.VenuePolicyStruct],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userRiskScores: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  venuePolicies: TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, string, bigint, bigint, bigint, bigint, boolean] & {
        enabled: boolean;
        executor: string;
        maxAmount: bigint;
        cooldownSeconds: bigint;
        maxQuoteAgeSeconds: bigint;
        minUserRiskScore: bigint;
        requiresRecipientMatch: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executePolicyAction"
  ): TypedContractMethod<
    [request: PolicyRouter.ExecutionRequestStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastExecutionAt"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "policyAdmins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setAllowedToken"
  ): TypedContractMethod<
    [token: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[nextPaused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicyAdmin"
  ): TypedContractMethod<
    [admin: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserRiskScore"
  ): TypedContractMethod<
    [user: AddressLike, riskScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVenuePolicy"
  ): TypedContractMethod<
    [venueIdHash: BytesLike, policy: PolicyRouter.VenuePolicyStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRiskScores"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "venuePolicies"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [boolean, string, bigint, bigint, bigint, bigint, boolean] & {
        enabled: boolean;
        executor: string;
        maxAmount: bigint;
        cooldownSeconds: bigint;
        maxQuoteAgeSeconds: bigint;
        minUserRiskScore: bigint;
        requiresRecipientMatch: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnerTransferred"
  ): TypedContractEvent<
    OwnerTransferredEvent.InputTuple,
    OwnerTransferredEvent.OutputTuple,
    OwnerTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyActionExecuted"
  ): TypedContractEvent<
    PolicyActionExecutedEvent.InputTuple,
    PolicyActionExecutedEvent.OutputTuple,
    PolicyActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyAdminSet"
  ): TypedContractEvent<
    PolicyAdminSetEvent.InputTuple,
    PolicyAdminSetEvent.OutputTuple,
    PolicyAdminSetEvent.OutputObject
  >;
  getEvent(
    key: "RouterPaused"
  ): TypedContractEvent<
    RouterPausedEvent.InputTuple,
    RouterPausedEvent.OutputTuple,
    RouterPausedEvent.OutputObject
  >;
  getEvent(
    key: "TokenAllowed"
  ): TypedContractEvent<
    TokenAllowedEvent.InputTuple,
    TokenAllowedEvent.OutputTuple,
    TokenAllowedEvent.OutputObject
  >;
  getEvent(
    key: "UserRiskScoreSet"
  ): TypedContractEvent<
    UserRiskScoreSetEvent.InputTuple,
    UserRiskScoreSetEvent.OutputTuple,
    UserRiskScoreSetEvent.OutputObject
  >;
  getEvent(
    key: "VenuePolicySet"
  ): TypedContractEvent<
    VenuePolicySetEvent.InputTuple,
    VenuePolicySetEvent.OutputTuple,
    VenuePolicySetEvent.OutputObject
  >;

  filters: {
    "OwnerTransferred(address,address)": TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;
    OwnerTransferred: TypedContractEvent<
      OwnerTransferredEvent.InputTuple,
      OwnerTransferredEvent.OutputTuple,
      OwnerTransferredEvent.OutputObject
    >;

    "PolicyActionExecuted(address,bytes32,uint8,address,uint256,address)": TypedContractEvent<
      PolicyActionExecutedEvent.InputTuple,
      PolicyActionExecutedEvent.OutputTuple,
      PolicyActionExecutedEvent.OutputObject
    >;
    PolicyActionExecuted: TypedContractEvent<
      PolicyActionExecutedEvent.InputTuple,
      PolicyActionExecutedEvent.OutputTuple,
      PolicyActionExecutedEvent.OutputObject
    >;

    "PolicyAdminSet(address,bool)": TypedContractEvent<
      PolicyAdminSetEvent.InputTuple,
      PolicyAdminSetEvent.OutputTuple,
      PolicyAdminSetEvent.OutputObject
    >;
    PolicyAdminSet: TypedContractEvent<
      PolicyAdminSetEvent.InputTuple,
      PolicyAdminSetEvent.OutputTuple,
      PolicyAdminSetEvent.OutputObject
    >;

    "RouterPaused(bool)": TypedContractEvent<
      RouterPausedEvent.InputTuple,
      RouterPausedEvent.OutputTuple,
      RouterPausedEvent.OutputObject
    >;
    RouterPaused: TypedContractEvent<
      RouterPausedEvent.InputTuple,
      RouterPausedEvent.OutputTuple,
      RouterPausedEvent.OutputObject
    >;

    "TokenAllowed(address,bool)": TypedContractEvent<
      TokenAllowedEvent.InputTuple,
      TokenAllowedEvent.OutputTuple,
      TokenAllowedEvent.OutputObject
    >;
    TokenAllowed: TypedContractEvent<
      TokenAllowedEvent.InputTuple,
      TokenAllowedEvent.OutputTuple,
      TokenAllowedEvent.OutputObject
    >;

    "UserRiskScoreSet(address,uint8)": TypedContractEvent<
      UserRiskScoreSetEvent.InputTuple,
      UserRiskScoreSetEvent.OutputTuple,
      UserRiskScoreSetEvent.OutputObject
    >;
    UserRiskScoreSet: TypedContractEvent<
      UserRiskScoreSetEvent.InputTuple,
      UserRiskScoreSetEvent.OutputTuple,
      UserRiskScoreSetEvent.OutputObject
    >;

    "VenuePolicySet(bytes32,address,bool,uint128,uint32,uint32,uint8,bool)": TypedContractEvent<
      VenuePolicySetEvent.InputTuple,
      VenuePolicySetEvent.OutputTuple,
      VenuePolicySetEvent.OutputObject
    >;
    VenuePolicySet: TypedContractEvent<
      VenuePolicySetEvent.InputTuple,
      VenuePolicySetEvent.OutputTuple,
      VenuePolicySetEvent.OutputObject
    >;
  };
}
