"use client";

import { useState } from "react";
import {
  type FxRates,
  type LocalCurrency,
  CURRENCY_META,
  convertUSD,
  formatLocal,
} from "../lib/currency";

export type ReceiptTx = {
  hash: string;
  timestamp: number;
  type: string;
  amount: string;
  token: string;
  counterparty: string;
  counterpartyLabel: string;
  contactName: string;
  note: string;
};

type Props = {
  tx: ReceiptTx;
  walletAddress: string;
  localCurrency: LocalCurrency;
  fxRates: FxRates | null;
  onClose: () => void;
};

function shorten(addr: string) {
  return addr.length > 12 ? `${addr.slice(0, 6)}…${addr.slice(-4)}` : addr;
}

function formatDate(ts: number) {
  return new Date(ts * 1000).toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" });
}

function typeLabel(type: string) {
  if (type === "received") return "RECEIVED";
  if (type === "failed") return "FAILED";
  if (type === "contract") return "CONTRACT";
  return "SENT";
}

function typeEmoji(type: string) {
  if (type === "received") return "↓";
  if (type === "failed") return "✕";
  return "↑";
}

async function generatePDF(tx: ReceiptTx, walletAddress: string, localLine: string | null) {
  const payload = {
    hash: tx.hash, timestamp: tx.timestamp, type: tx.type,
    amount: tx.amount, token: tx.token,
    counterparty: tx.counterparty, contactName: tx.contactName,
    note: tx.note, walletAddress, localLine,
  };

  // iOS — Web Share API with file works fine
  const testFile = new File([new Blob([""], { type: "application/pdf" })], "t.pdf", { type: "application/pdf" });
  if (navigator.canShare?.({ files: [testFile] })) {
    const { jsPDF } = await import("jspdf");
    const W = 80;
    const doc = new jsPDF({ unit: "mm", format: [W, 150], orientation: "portrait" });
    const dark:  [number, number, number] = [26, 21, 5];
    const green: [number, number, number] = [34, 197, 94];
    const mid:   [number, number, number] = [100, 95, 80];
    const light: [number, number, number] = [244, 241, 234];

    doc.setFillColor(...dark); doc.rect(0, 0, W, 28, "F");
    doc.setFillColor(...green); doc.circle(W / 2, 14, 7, "F");
    doc.setFont("helvetica", "bold"); doc.setFontSize(12); doc.setTextColor(...dark);
    doc.text(typeEmoji(tx.type), W / 2, 16.5, { align: "center" });
    doc.setFontSize(7); doc.setTextColor(...green); doc.text("AKILI", 4, 6);
    doc.setTextColor(...mid); doc.setFont("helvetica", "normal"); doc.text("PAYMENT RECEIPT", W - 4, 6, { align: "right" });
    doc.setFont("helvetica", "bold"); doc.setFontSize(7.5); doc.setTextColor(...light);
    doc.text(typeLabel(tx.type), W / 2, 26, { align: "center" });

    let y = 36;
    doc.setFontSize(22); doc.setTextColor(...dark);
    doc.text(`${parseFloat(tx.amount).toFixed(2)}`, W / 2, y, { align: "center" }); y += 5;
    doc.setFont("helvetica", "normal"); doc.setFontSize(8.5); doc.setTextColor(...mid);
    doc.text(`${tx.token} · Celo Network`, W / 2, y, { align: "center" }); y += 4;
    if (localLine) {
      doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(...green);
      doc.text(`≈ ${localLine}`, W / 2, y, { align: "center" }); y += 4;
    }
    y += 3; doc.setDrawColor(220, 215, 200); doc.line(6, y, W - 6, y); y += 6;

    const isOut = tx.type === "sent" || tx.type === "contract";
    const rows: [string, string][] = [
      [isOut ? "To" : "From", tx.contactName !== shorten(tx.counterparty) ? tx.contactName : shorten(tx.counterparty)],
      [isOut ? "From" : "To", "Your wallet"],
      ["Date", formatDate(tx.timestamp)], ["Network", "Celo Mainnet"],
      ...(tx.note ? [["Note", tx.note] as [string, string]] : []),
      ["Ref", shorten(tx.hash)],
    ];
    doc.setFontSize(7.5);
    for (const [label, value] of rows) {
      doc.setFont("helvetica", "bold"); doc.setTextColor(...mid); doc.text(label, 6, y);
      doc.setFont("helvetica", "normal"); doc.setTextColor(...dark);
      const wrapped = doc.splitTextToSize(value, 42) as string[];
      doc.text(wrapped, W - 6, y, { align: "right" });
      y += wrapped.length > 1 ? wrapped.length * 4.5 : 6;
    }
    y += 1; doc.setDrawColor(220, 215, 200); doc.line(6, y, W - 6, y); y += 5;
    doc.setFont("helvetica", "normal"); doc.setFontSize(6); doc.setTextColor(...mid);
    doc.text("Verified on Celo Blockchain", W / 2, y, { align: "center" }); y += 4;
    doc.text("Generated by Akili · Built on Celo", W / 2, y, { align: "center" });

    const date = new Date(tx.timestamp * 1000).toISOString().slice(0, 10);
    const filename = `akili-receipt-${tx.hash.slice(2, 8)}-${date}.pdf`;
    const blob = doc.output("blob");
    await navigator.share({
      files: [new File([blob], filename, { type: "application/pdf" })],
      title: `Akili Receipt · ${parseFloat(tx.amount).toFixed(2)} ${tx.token}`,
      text: `Payment receipt${localLine ? ` (≈ ${localLine})` : ""} · Verified on Celo`,
    });
    return;
  }

  // Android WebView + Desktop — blob: URIs are blocked, use server-generated real HTTPS URL
  const res = await fetch("/api/receipt", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  if (!res.ok) throw new Error("Could not prepare receipt — please try again.");
  const { id } = await res.json() as { id: string };
  window.open(`/api/receipt?id=${id}`, "_blank");
}

export function ReceiptModal({ tx, walletAddress, localCurrency, fxRates, onClose }: Props) {
  const [generating, setGenerating] = useState(false);

  const isOut = tx.type === "sent" || tx.type === "contract";
  const amt = parseFloat(tx.amount);

  // Only show local currency for received — sent could be a withdrawal via Quidax
  const localLine = (!isOut && fxRates && localCurrency !== "USD")
    ? formatLocal(convertUSD(amt, localCurrency, fxRates), localCurrency)
    : null;

  const meta = CURRENCY_META[localCurrency];

  async function handleShare() {
    setGenerating(true);
    try {
      await generatePDF(tx, walletAddress, localLine);
    } catch {
      // share cancelled or failed — silently ignore
    } finally {
      setGenerating(false);
    }
  }

  return (
    <>
      {/* Backdrop */}
      <div
        onClick={onClose}
        style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.45)", backdropFilter: "blur(4px)", zIndex: 200 }}
      />

      {/* Sheet */}
      <div style={{
        position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)",
        width: "min(100%, 390px)", zIndex: 201,
        background: "var(--bg)", borderRadius: "24px 24px 0 0",
        padding: "0 0 calc(24px + env(safe-area-inset-bottom))",
        boxShadow: "0 -8px 40px rgba(0,0,0,0.18)"
      }}>
        {/* Drag handle */}
        <div style={{ display: "flex", justifyContent: "center", padding: "12px 0 0" }}>
          <div style={{ width: "36px", height: "4px", borderRadius: "2px", background: "var(--line)" }} />
        </div>

        {/* Receipt card */}
        <div style={{ margin: "12px 16px 0", borderRadius: "20px", overflow: "hidden", border: "1px solid var(--line)", boxShadow: "0 4px 24px rgba(0,0,0,0.1)" }}>

          {/* Header */}
          <div style={{
            background: "var(--slab)", padding: "20px 16px 16px",
            display: "flex", flexDirection: "column", alignItems: "center", gap: "8px"
          }}>
            <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", width: "100%" }}>
              <span style={{ fontSize: "10px", fontWeight: 800, color: "var(--green)", letterSpacing: "0.08em" }}>AKILI</span>
              <span style={{ fontSize: "9px", color: "var(--slab-ink-40)", letterSpacing: "0.06em" }}>PAYMENT RECEIPT</span>
            </div>

            <div style={{
              width: "44px", height: "44px", borderRadius: "50%",
              background: "var(--green)", display: "flex", alignItems: "center", justifyContent: "center",
              fontSize: "20px", fontWeight: 700, color: "var(--slab)"
            }}>
              {typeEmoji(tx.type)}
            </div>

            <div style={{ fontSize: "10px", fontWeight: 700, letterSpacing: "0.1em", color: "var(--slab-ink-70)" }}>
              {typeLabel(tx.type)}
            </div>

            <div style={{ textAlign: "center" }}>
              <div style={{ fontSize: "28px", fontWeight: 700, fontFamily: "var(--font-mono)", color: "var(--slab-ink)", letterSpacing: "-0.04em", lineHeight: 1 }}>
                {parseFloat(tx.amount).toFixed(2)}
              </div>
              <div style={{ fontSize: "12px", color: "var(--slab-ink-70)", marginTop: "3px" }}>
                {tx.token} · Celo
              </div>
              {localLine && (
                <div style={{ fontSize: "13px", fontWeight: 700, color: "var(--green)", marginTop: "4px" }}>
                  ≈ {localLine}
                </div>
              )}
            </div>
          </div>

          {/* Details */}
          <div style={{ background: "var(--surface)", padding: "14px 16px", display: "flex", flexDirection: "column", gap: "0" }}>
            {[
              [isOut ? "To" : "From", tx.contactName !== tx.counterpartyLabel ? tx.contactName : shorten(tx.counterparty)],
              [isOut ? "From" : "To", "Your wallet"],
              ["Date", formatDate(tx.timestamp)],
              ["Network", "Celo Mainnet"],
              ...(tx.note ? [["Note", tx.note]] : []),
              ["Reference", shorten(tx.hash)],
            ].map(([label, value], i, arr) => (
              <div
                key={label}
                style={{
                  display: "flex", justifyContent: "space-between", alignItems: "flex-start",
                  padding: "9px 0",
                  borderBottom: i < arr.length - 1 ? "1px solid var(--line)" : "none",
                  gap: "12px"
                }}
              >
                <span style={{ fontSize: "11px", color: "var(--ink-55)", fontWeight: 600, flexShrink: 0 }}>{label}</span>
                <span style={{ fontSize: "11px", color: "var(--ink)", fontFamily: label === "Reference" || label === "To" || label === "From" ? "var(--font-mono)" : "inherit", textAlign: "right", wordBreak: "break-all" }}>{value}</span>
              </div>
            ))}
          </div>

          {/* Verified footer */}
          <div style={{
            background: "var(--bg-soft)", borderTop: "1px solid var(--line)",
            padding: "10px 16px", textAlign: "center"
          }}>
            <span style={{ fontSize: "10px", color: "var(--ink-40)" }}>
              ● Verified on Celo Blockchain · Generated by Akili
            </span>
          </div>
        </div>

        {/* Actions */}
        <div style={{ padding: "14px 16px 0", display: "flex", gap: "10px" }}>
          <button
            type="button"
            onClick={() => void handleShare()}
            disabled={generating}
            style={{
              flex: 1, padding: "14px", borderRadius: "999px", border: "none",
              background: generating ? "var(--line)" : "var(--ink)",
              color: "#fffdf7", fontSize: "14px", fontWeight: 700,
              cursor: generating ? "not-allowed" : "pointer"
            }}
          >
            {generating ? "Generating…" : "Share Receipt"}
          </button>
          <button
            type="button"
            onClick={onClose}
            style={{
              padding: "14px 20px", borderRadius: "999px",
              border: "1px solid var(--line)", background: "transparent",
              fontSize: "14px", fontWeight: 600, color: "var(--ink-55)", cursor: "pointer"
            }}
          >
            Close
          </button>
        </div>

        {localLine && isOut === false && (
          <p style={{ fontSize: "10px", color: "var(--ink-40)", textAlign: "center", margin: "8px 16px 0", lineHeight: 1.4 }}>
            ≈ {meta.label} equivalent at current rate · actual amount may vary
          </p>
        )}
      </div>
    </>
  );
}
